name: CI

on:
  pull_request:
  push:
    paths-ignore:
    - '**/*.md'
    - '**/*.org'
    - '.dir-locals.el'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental || matrix.emacs_version == 'snapshot' }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        emacs_version: [26.1, 26.2, 26.3, 27.1, 27.2, 28.1, 28.2, 29.1, 29.3, 30.1, 30.2, snapshot]
        experimental: [false]

        # Exclude Emacs versions that are unavailable on Apple Silicon
        exclude:
          - emacs_version: 26.1
            os: macos-latest
          - emacs_version: 26.2
            os: macos-latest
          - emacs_version: 26.3
            os: macos-latest
          - emacs_version: 27.1
            os: macos-latest
          - emacs_version: 27.2
            os: macos-latest
          - emacs_version: 28.1
            os: macos-latest
        include:
          - emacs_version: snapshot
            ledger_version: github:ledger/ledger#ledger
            experimental: true
            os: ubuntu-latest

    steps:
    - uses: cachix/install-nix-action@v31
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - uses: purcell/setup-emacs@master
      with:
        version: ${{ matrix.emacs_version }}

    - uses: actions/checkout@v6
    - name: Byte compilation
      run: emacs --eval "(setq byte-compile-error-on-warn t)" -L . --batch -f batch-byte-compile ./*.el
    - name: Tests
      run: nix shell 'nixpkgs#getopt' ${{ matrix.ledger_version || 'nixpkgs#ledger' }} --print-build-logs -c ./makem.sh test -vv
    # This is currently for information only, since a lot of docstrings need fixing up
    - name: Checkdoc
      run: make lint-checkdoc || true
    # TODO: Run other makem.sh lints
